version: "3.8"

services:
  # ai
  ollama:
    image: ollama/ollama:latest
    container_name: my-ai-brain
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # back-end
  backend:
    build: ./server # Dockerfile
    container_name: my-backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama

volumes:
  ollama_data:
